# Generated by Django 4.1.7 on 2023-03-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bet",
            options={"ordering": ["race_id"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="bet",
            name="beer",
            field=models.BooleanField(default=False),
        ),
    ]
