# Generated by Django 4.1.7 on 2023-03-07 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0002_alter_bet_options_alter_driver_options_bet_beer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bet",
            options={"ordering": ["race_id", "person_id"]},
        ),
        migrations.AlterModelOptions(
            name="race",
            options={"ordering": ["race_date"]},
        ),
        migrations.AddField(
            model_name="race",
            name="tv",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="driver",
            name="name",
            field=models.CharField(default="", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="race",
            name="race_date",
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(default="", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(default="", max_length=32, unique=True),
        ),
    ]
