# Generated by Django 4.1.7 on 2023-03-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0004_tv_alter_race_tv"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="tv_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="www.tv"
            ),
        ),
    ]
