# Generated by Django 4.1.7 on 2023-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0007_tv_createdat_tv_updatedat_tv_user_alter_tv_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="web_site",
            field=models.URLField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="race",
            name="web_site",
            field=models.URLField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="web_site",
            field=models.URLField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="track",
            name="web_site",
            field=models.URLField(max_length=128, null=True, unique=True),
        ),
    ]
