# Generated by Django 4.1.7 on 2023-03-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("www", "0008_driver_web_site_race_web_site_team_web_site_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="bet",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.AlterField(
            model_name="tv",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="tv",
            name="updatedAt",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="date last updated"
            ),
        ),
        migrations.CreateModel(
            name="CrewChief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="date created"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date last updated"
                    ),
                ),
                ("name", models.CharField(default="???", max_length=64, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="crew_chief_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="www.crewchief",
            ),
        ),
    ]
