# Generated by Django 4.1.7 on 2023-03-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0009_alter_person_options_alter_bet_createdat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewchief",
            name="team_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="www.team"
            ),
        ),
    ]
