# Generated by Django 4.1.7 on 2023-03-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0012_result_driver_id_result_finished_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["name"], "verbose_name": "Player"},
        ),
        migrations.AlterField(
            model_name="driver",
            name="team_id",
            field=models.ForeignKey(
                default=-1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="www.team",
            ),
        ),
    ]
