# Generated by Django 4.1.7 on 2023-03-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0013_alter_person_options_alter_driver_team_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="team_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="www.team"
            ),
        ),
    ]
